name: Snyk Security Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Snyk
        run: npx snyk auth $SNYK_TOKEN

      - name: Run Snyk test
        run: npx snyk test
